mysite-project/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [path('', views.index, name='index'),
               path('portfolio', views.portfolio, name='portfolio'),
               path('portfolio_edu_add', views.portfolio_edu_add, name='portfolio_edu_add'),
               path('portfolio_work_add', views.portfolio_work_add, name='portfolio_work_add'),
               path('portfolio_project_add', views.portfolio_project_add, name='portfolio_project_add'),
               path('portfolio_honor_add', views.portfolio_honor_add, name='portfolio_honor_add'),
               path('portfolio_language_add', views.portfolio_language_add, name='portfolio_language_add'),
               path('portfolio_programming_language_add', views.portfolio_programming_language_add,
                    name='portfolio_programming_language_add'),
               path('portfolio_hobby_add', views.portfolio_hobby_add, name='portfolio_hobby_add'),
               path('blog_index', views.blog_index, name='blog_index'),
               path('blog_detail/<int:pk>/', views.blog_detail, name='blog_detail'),
               path('blog_archives/<int:year>/<int:month>/', views.blog_archive, name='blog_archive'),
               path('blog_categories/<int:pk>/', views.blog_category, name='blog_category'),
               path('blog_tags/<int:pk>/', views.blog_tag, name='blog_tag'),
               path('search/', views.search, name='search'),
               ]

mysite-project/comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

mysite-project/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('summernote/', include('django_summernote.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

mysite-project/comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

mysite-project/comments/forms.py
from django import forms
from .models import Comment
# from django_summernote.fields import SummernoteTextFormField


class CommentForm(forms.ModelForm):
    # text = SummernoteTextFormField()
    class Meta:
        model = Comment
        fields = ['name', 'email', 'text']

mysite-project/comments/views.py
from django.shortcuts import render

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

# Create your views here.

from blog.models import Post
from .forms import CommentForm


@require_POST
def comment(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    form = CommentForm(request.POST)

    if form.is_valid():

        # Commit =False is used to simply generate an instance of the Comment model class from the form's data,
        # but does not yet save the Comment data to the database.
        comment = form.save(commit=False)

        # Associate the comment with the article being commented on.
        comment.post = post

        # Finally saves the comment data to the database and calls the save method of the model instance
        comment.save()

        messages.add_message(request, messages.SUCCESS, 'Success!', extra_tags='success')

        # Redirect to the Detail page of the Post,
        # which in fact calls the get_absolute_URL method of the model instance.
        # When the Redirect function receives an instance of the model,
        # then redirect to the URL returned by the get_absolute_URL method.
        return redirect(post)

    # After checking that the data is not valid, we render a preview page to show the error of the form.
    # Note that the post that was commented on here is also passed to the template
    # because we need to generate the submission address of the form based on post.
    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, 'ERROR！Please modify the errors in the form and resubmit.', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

mysite-project/templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-6">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div id="text" class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn" style="float: right">Submit</button>
        </div>
    </div>    <!-- row -->
</form>

mysite-project/templates/comments/inclusions/_list.html
<h3>
    {% if comment_count == 1 %}
        There is <span>{{ comment_count }}</span> comment.
    {% else %}
        There are <span>{{ comment_count }}</span> comments.
    {% endif %}
</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
        <li class="comment-item">
            <span class="nickname">{{ comment.name }}</span>
            <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
            <div class="text">
                {{ comment.text|safe|linebreaks }}
            </div>
        </li>
    {% empty %}
        Currently No Comments...
    {% endfor %}
</ul>