mysite-project/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [path('', views.index, name='index'),
               path('portfolio', views.portfolio, name='portfolio'),
               path('portfolio_edu_add', views.portfolio_edu_add, name='portfolio_edu_add'),
               path('portfolio_work_add', views.portfolio_work_add, name='portfolio_work_add'),
               path('portfolio_project_add', views.portfolio_project_add, name='portfolio_project_add'),
               path('portfolio_honor_add', views.portfolio_honor_add, name='portfolio_honor_add'),
               path('portfolio_language_add', views.portfolio_language_add, name='portfolio_language_add'),
               path('portfolio_programming_language_add', views.portfolio_programming_language_add,
                    name='portfolio_programming_language_add'),
               path('portfolio_hobby_add', views.portfolio_hobby_add, name='portfolio_hobby_add'),
               path('blog_index', views.blog_index, name='blog_index'),
               path('blog_detail/<int:pk>/', views.blog_detail, name='blog_detail'),
               path('blog_archives/<int:year>/<int:month>/', views.blog_archive, name='blog_archive'),
               path('blog_categories/<int:pk>/', views.blog_category, name='blog_category'),
               path('blog_tags/<int:pk>/', views.blog_tag, name='blog_tag'),
               path('search/', views.search, name='search'),
               ]

mysite-project/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('summernote/', include('django_summernote.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

mysite-project/blog/models.py
import markdown
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.html import strip_tags

# Create your models here.

"""
django 内置的全部类型可查看文档：
https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types
ForeignKey、ManyToManyField 不了解，可参考官方文档：
https://docs.djangoproject.com/en/2.2/topics/db/models/#relationships
"""


class Education(models.Model):
    name_of_education = models.CharField(max_length=100)
    start_date_of_education = models.DateField(blank=True, null=True)
    end_date_of_education = models.DateField(blank=True, null=True)
    details_of_education = models.TextField()

    def __str__(self):
        return self.name_of_education


class WorkExperience(models.Model):
    name_of_work_and_internship = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)
    start_date_of_work_and_internship = models.DateField(blank=True, null=True)
    end_date_of_work_and_internship = models.DateField(blank=True, null=True)
    details_of_work_and_internship = models.TextField()

    def __str__(self):
        return self.name_of_work_and_internship


class Project(models.Model):
    name_of_project_experience = models.CharField(max_length=100)
    project_job_title = models.CharField(max_length=100)
    start_date_of_project_experience = models.DateField(blank=True, null=True)
    end_date_of_project_experience = models.DateField(blank=True, null=True)
    details_of_project_experience = models.TextField()

    def __str__(self):
        return self.name_of_project_experience


class LanguageSkill(models.Model):
    language_skills = models.CharField(max_length=100)

    def __str__(self):
        return self.language_skills


class ProgrammingLanguageSkill(models.Model):
    programming_language_skill = models.CharField(max_length=100)
    programming_language_skill_details = models.TextField(blank=True)
    programming_language_skill_details_rich = models.TextField(blank=True)

    def __str__(self):
        return self.programming_language_skill


class Honor(models.Model):
    name_of_the_honor = models.CharField(max_length=200)

    def __str__(self):
        return self.name_of_the_honor


class PersonalHobby(models.Model):
    personal_hobby = models.CharField(max_length=100)

    def __str__(self):
        return self.personal_hobby


class Category(models.Model):
    """
    Category of my blog
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    Blog Tag
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    Blog post database
    """

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=70)
    abstract = models.CharField(max_length=200, blank=True)
    text = models.TextField(blank=True)
    text_rich = models.TextField(blank=True)
    views = models.PositiveIntegerField(default=0, editable=False)

    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    modified_date = models.DateTimeField(blank=True, null=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ['-created_date', 'title']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.abstract:
            self.modified_date = timezone.now()
            super().save(*args, **kwargs)
        else:
            self.modified_date = timezone.now()

            # First instantiates a Markdown class that renders the text of the text.
            # Since abstracts do not need to generate article directories, directory extensions are removed.
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])

            # First render the Markdown text as HTML text
            # strip_tags Strip out all HTML tags of HTML text
            # then give 54 chars to abstract
            if self.text:
                self.abstract = strip_tags(md.convert(self.text))[:50]
            else:
                self.abstract = strip_tags(md.convert(self.text_rich))[:50]

            super().save(*args, **kwargs)

    def __str__(self):
        return self.title

mysite-project/comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])

mysite-project/blog/forms.py
from django import forms
from django_summernote.fields import SummernoteTextFormField

from .models import *


class EducationForm(forms.ModelForm):
    details_of_education = SummernoteTextFormField()

    class Meta:
        model = Education
        fields = ['name_of_education', 'start_date_of_education', 'end_date_of_education', 'details_of_education']


class WorkExperienceForm(forms.ModelForm):
    details_of_work_and_internship = SummernoteTextFormField()

    class Meta:
        model = WorkExperience
        fields = ['name_of_work_and_internship', 'job_title', 'start_date_of_work_and_internship',
                  'end_date_of_work_and_internship', 'details_of_work_and_internship']


class ProjectForm(forms.ModelForm):
    details_of_project_experience = SummernoteTextFormField()

    class Meta:
        model = Project
        fields = ['name_of_project_experience', 'project_job_title', 'start_date_of_project_experience',
                  'end_date_of_project_experience', 'details_of_project_experience']


class LanguageForm(forms.ModelForm):
    class Meta:
        model = LanguageSkill
        fields = ['language_skills']


class ProgrammingLanguageForm(forms.ModelForm):
    programming_language_skill_details = SummernoteTextFormField()

    class Meta:
        model = ProgrammingLanguageSkill
        fields = ['programming_language_skill', 'programming_language_skill_details']


class HonorForm(forms.ModelForm):
    class Meta:
        model = Honor
        fields = ['name_of_the_honor']


class PersonalHobbyForm(forms.ModelForm):
    class Meta:
        model = PersonalHobby
        fields = ['personal_hobby']

mysite-project/blog/views.py
import re

import markdown
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from .forms import EducationForm, WorkExperienceForm, ProjectForm, LanguageForm, ProgrammingLanguageForm, HonorForm, \
    PersonalHobbyForm
from .models import *


# Create your views here.

def index(request):  # Home Page
    return render(request, 'blog/index.html')


def blog_index(request):
    post_list = Post.objects.order_by('-created_date')
    return render(request, 'blog/blog_index.html', context={'post_list': post_list})


"""

In the self-built MySQL database, the time zone table mysql.time_zone is empty by default,
Django configuration file Settings if USE_TZ = True,
Django USES database queries with time zones.
This results in no data being queried from MySQL.
There are two solutions:

1. Set USE_TZ=False

print(Article.objects.filter(created_time__month=5).query)
SELECT
    `blog_article`.`id`,
    `blog_article`.`title`,
    `blog_article`.`body`,
    `blog_article`.`created_time`,
    `blog_article`.`modified_time`,
    `blog_article`.`abstract`,
    `blog_article`.`category_id`,
    `blog_article`.`author_id` 
FROM
    `blog_article` 
WHERE
    EXTRACT( MONTH FROM `blog_article`.`created_time` ) = 5


# USE_TZ=True时的MySQL语句
print(Article.objects.filter(created_time__month=5).query)  
SELECT
    `blog_article`.`id`,
    `blog_article`.`title`,
    `blog_article`.`body`,
    `blog_article`.`created_time`,
    `blog_article`.`modified_time`,
    `blog_article`.`abstract`,
    `blog_article`.`category_id`,
    `blog_article`.`author_id` 
FROM
    `blog_article` 
WHERE
    EXTRACT(MONTH FROM CONVERT_TZ( `blog_article`.`created_time`, 'UTC', 'Asia/Shanghai' )) = 5

2. Import time zone data into MySQL
On Linux, execute the following command in the Shell to import the time zone into the MySQL database

$ mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p

"""


def blog_archive(request, year, month):
    post_list = Post.objects.filter(created_date__year=year,
                                    created_date__month=month,
                                    ).order_by('-created_date')
    return render(request, 'blog/blog_index.html', context={'post_list': post_list})


def blog_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=category).order_by('-created_date')
    return render(request, 'blog/blog_index.html', context={'post_list': post_list})


def blog_tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=tag).order_by('-created_date')
    return render(request, 'blog/blog_index.html', context={'post_list': post_list})


def blog_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # Views +1
    post.increase_views()

    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    post.text = md.convert(post.text)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''
    return render(request, 'blog/blog_detail.html', context={'post': post})


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "Please enter keywords"
        messages.add_message(request, messages.ERROR, error_msg, extra_tags='danger')
        return redirect('blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(text__icontains=q) | Q(text_rich__icontains=q))
    return render(request, 'blog/blog_index.html', {'post_list': post_list})


def portfolio(request):  # My Resume
    educations = Education.objects.order_by('id')
    projects = Project.objects.order_by('id')
    honors = Honor.objects.order_by('id')
    hobbies = PersonalHobby.objects.order_by('id')
    work_experiences = WorkExperience.objects.order_by('id')
    language_skills = LanguageSkill.objects.order_by('id')
    programming_skills = ProgrammingLanguageSkill.objects.order_by('id')

    context = {'educations': educations,
               'projects': projects,
               'honors': honors,
               'hobbies': hobbies,
               'work_experiences': work_experiences,
               'language_skills': language_skills,
               'programming_skills': programming_skills}

    return render(request, 'blog/portfolio.html', context=context)


def portfolio_edu_add(request):
    if request.method == 'POST':
        education_form = EducationForm(request.POST)

        if education_form.is_valid():
            education_form.save()
            return HttpResponseRedirect('/portfolio')

    education_form = EducationForm()

    context = {
        'education_form': education_form,
    }

    return render(request, 'blog/portfolio_edu_add.html', context=context)


def portfolio_work_add(request):
    if request.method == 'POST':
        work_form = WorkExperienceForm(request.POST)

        if work_form.is_valid():
            work_form.save()
            return HttpResponseRedirect('/portfolio')

    work_form = WorkExperienceForm()
    context = {
        'work_form': work_form,
    }

    return render(request, 'blog/portfolio_work_add.html', context=context)


def portfolio_project_add(request):
    if request.method == 'POST':
        project_form = ProjectForm(request.POST)

        if project_form.is_valid():
            project_form.save()
            return HttpResponseRedirect('/portfolio')

    project_form = ProjectForm()
    context = {
        'project_form': project_form,
    }

    return render(request, 'blog/portfolio_project_add.html', context=context)


def portfolio_language_add(request):
    if request.method == 'POST':
        language_form = LanguageForm(request.POST)

        if language_form.is_valid():
            language_form.save()
            return HttpResponseRedirect('/portfolio')

    language_form = LanguageForm()
    context = {
        'language_form': language_form,
    }

    return render(request, 'blog/portfolio_language_add.html', context=context)


def portfolio_programming_language_add(request):
    if request.method == 'POST':
        programming_language_form = ProgrammingLanguageForm(request.POST)

        if programming_language_form.is_valid():
            programming_language_form.save()
            return HttpResponseRedirect('/portfolio')

    programming_language_form = ProgrammingLanguageForm()
    context = {
        'programming_language_form': programming_language_form,
    }

    return render(request, 'blog/portfolio_programming_language_add.html', context=context)


def portfolio_honor_add(request):
    if request.method == 'POST':
        honor_form = HonorForm(request.POST)

        if honor_form.is_valid():
            honor_form.save()
            return HttpResponseRedirect('/portfolio')

    honor_form = HonorForm()
    context = {
        'honor_form': honor_form,
    }

    return render(request, 'blog/portfolio_honor_add.html', context=context)


def portfolio_hobby_add(request):
    if request.method == 'POST':
        personal_hobby_form = PersonalHobbyForm(request.POST)

        if personal_hobby_form.is_valid():
            personal_hobby_form.save()
            return HttpResponseRedirect('/portfolio')

    personal_hobby_form = PersonalHobbyForm()
    context = {
        'personal_hobby_form': personal_hobby_form
    }

    return render(request, 'blog/portfolio_hobby_add.html', context=context)

mysite-project/templates/blog/all_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Base Page Of My Blog">
    <meta name="author" content="Wenhan Wei">

    <title>WenhanWei's Blog</title>
    <link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}">

    <!-- Bootstrap core CSS -->
    <link href='{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}' rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'blog/vendor/ionicons-2.0.1/css/ionicons.min.css' %}">
    <link href="{% static 'blog/css/pace.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">

    <!--Code Highlight-->
    <link href="{% static 'blog/css/highlights/github.css' %}" rel="stylesheet">
    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'blog:index' %}">Welcome {{ user.username }}</a>
        {% else %}
            <a class="navbar-brand" href="{% url 'blog:index' %}">Welcome</a>
        {% endif %}
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" id="home" href="{% url 'blog:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="blog" href="{% url 'blog:blog_index' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="portfolio" href="{% url 'blog:portfolio' %}">About Me</a>
                </li>
            </ul>
            {% block searchField %}
            {% endblock %}
        </div>

    </div>
</nav>




{% block content %}
{% endblock %}



<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://github.com/WenhanWei">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="mailto:weiwenhan0702@outlook.com">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="{% static 'blog/Wenhan Wei _University of Birmingham_Computer Science_Undergraduate.pdf' %}"
                           download>
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="far fa-file-pdf fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <!--
                  <li class="list-inline-item">
                    <a href="#">
                      <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                    <li class="list-inline-item">
                    <a href="#">
                      <span class="fa-stack fa-lg">
                        <i class="fas fa-circle fa-stack-2x"></i>
                        <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                   -->
                </ul>
                <p class="copyright text-muted">Copyright &copy; 2020 WenhanWei </p>
            </div>
        </div>
    </div>
</footer>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'blog/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static "blog/js/clean-blog.min.js" %}"></script>
<script src="{% static "blog/js/pace.min.js" %}"></script>
<script src="{% static "blog/js/modernizr.custom.js" %}"></script>

<script src="{% static 'blog/js/highlight.min-9.15.8.js' %}"></script>
<script src="{% static 'blog/js/highlightjs-line-numbers.min-2.7.0.js' %}"></script>

</body>
</html>

mysite-project/templates/blog/portfolio.html
{% extends 'blog/all_base.html' %}
{% load static %}
{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'blog/img/University_of_Birmingham.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Wenhan Wei</h1>
                        <span class="subheading">School of Computer Science</span>
                        <span class="subheading">University of Birmingham</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8 blog-main">
                <!-- ******************  EDUCATION & CERTIFICATIONS ****************** -->
                {% if educations %}
                    <section class="education">
                        <h2>Education</h2>
                        <hr>
                        {% for education in educations %}
                            <h3>{{ education.name_of_education }}</h3>
                            <p class="blog-post-meta">{{ education.start_date_of_education }}-{{ education.end_date_of_education }}</p>
                            <p>{{ education.details_of_education |safe|linebreaksbr }}</p>
                        {% endfor %}
                    </section>
                {% endif %}

                {% if user.is_authenticated %}
                    <div>
                        <label>Manage Education: </label>
                        <button><a href="{% url 'blog:portfolio_edu_add' %}">Add</a></button>
                    </div>
                {% endif %}

                <!-- ***********************  WORK EXPERIENCE  *********************** -->
                {% if work_experiences %}
                    <section class="work-experience">
                        <h2>Work Experience</h2>
                        <hr>
                        {% for work_experience in work_experiences %}
                            <h3>{{ work_experience.name_of_work_and_internship }}</h3>
                            <p>{{ work_experience.start_date_of_work_and_internship }}-{{ work_experience.end_date_of_work_and_internship }}</p>
                            <p>{{ work_experience.job_title }}</p>
                            <p>{{ work_experience.details_of_work_and_internship | safe | linebreaksbr }}</p>
                        {% endfor %}
                    </section>
                {% endif %}
                {% if user.is_authenticated %}
                    <div>
                        <label>Manage Work Experience: </label>
                        <button><a href="{% url 'blog:portfolio_work_add' %}">Add</a></button>
                    </div>
                {% endif %}
                <!-- ********************  PROJECTS / PORTFOLIO  ********************* -->
                {% if projects %}
                    <section class="projects">
                        <h2>Projects</h2>
                        <hr>
                        {% for project in projects %}
                            <h3>{{ project.name_of_project_experience }}</h3>
                            <p>{{ project.start_date_of_project_experience }}-{{ project.end_date_of_project_experience }}</p>
                            <p>{{ project.project_job_title }}</p>
                            <p>{{ project.details_of_project_experience | safe | linebreaksbr }}</p>
                        {% endfor %}
                    </section>
                {% endif %}
                {% if user.is_authenticated %}
                    <div>
                        <label>Manage Project: </label>
                        <button><a href="{% url 'blog:portfolio_project_add' %}">Add</a></button>
                    </div>
                {% endif %}
                <!-- ***********************  HONORS  *********************** -->
                {% if honors %}
                    <section class="honors">
                        <h2>Honors</h2>
                        <hr>
                        {% for honor in honors %}
                            <p>{{ honor.name_of_the_honor }}</p>
                        {% endfor %}
                    </section>
                {% endif %}
                {% if user.is_authenticated %}
                    <div>
                        <label>Manage Honor: </label>
                        <button><a href="{% url 'blog:portfolio_honor_add' %}">Add</a></button>
                    </div>
                {% endif %}
                <!-- ***********************  SKILLS  *********************** -->
                {% if language_skills or programming_skills %}
                    <section class="skills">
                        <h2>Skills</h2>
                        <hr>
                        {% if language_skills %}
                            <h4>Language Skills</h4>
                            {% for language_skill in language_skills %}
                                <p>{{ language_skill.language_skills }}</p>
                            {% endfor %}
                        {% endif %}
                        {% if user.is_authenticated %}
                            <div>
                                <label>Manage Language: </label>
                                <button><a href="{% url 'blog:portfolio_language_add' %}">Add</a></button>
                            </div>
                        {% endif %}

                        {% if programming_skills %}
                            <hr>
                            <h4>Programming Skills</h4>
                            {% for programming_skill in programming_skills %}
                                <p>{{ programming_skill.programming_language_skill }}</p>
                                {% if programming_skill.programming_language_skill_details %}
                                    <p>{{ programming_skill.programming_language_skill_details | safe | linebreaksbr }}</p>
                                {% else %}
                                    <p>{{ programming_skill.programming_language_skill_details_rich | safe | linebreaksbr }}</p>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </section>
                {% endif %}
                {% if user.is_authenticated %}
                    <div>
                        <label>Manage Programming Language:</label>
                        <button><a href="{% url 'blog:portfolio_programming_language_add' %}">Add</a></button>
                    </div>
                {% endif %}

                <!-- *********************** Personal Hobbies  *********************** -->
                {% if hobbies %}
                    <section class="hobbies">
                        <h2>Personal Hobbies</h2>
                        <hr>
                        {% for hobby in hobbies %}
                            <p>{{ hobby.personal_hobby }}</p>
                        {% endfor %}
                    </section>
                {% endif %}
                {% if user.is_authenticated %}
                    <div>
                        <label>Manage Hobbies:</label>
                        <button><a href="{% url 'blog:portfolio_hobby_add' %}">Add</a></button>
                    </div>
                {% endif %}
            </div><!--main -->
        </div><!-- row -->
    </main><!--container -->

{% endblock %}